name: Deploy API to VPS

on:
   push:
      branches:
         - master

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Deploy to VPS
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USERNAME }}
              key: ${{ secrets.VPS_SSH_KEY }}
              script: |
                 echo "🚀 Iniciando deploy da API..."
                 cd ~/meu-servidor

                 echo " PASSO 1/3: Puxando código mais recente..."
                 # CORREÇÃO 1: Caminho da pasta confirmado para 'chess_analyzer'
                 git -C ~/chess_analyzer pull

                 echo " PASSO 2/3: Forçando a reconstrução da imagem sem cache..."
                 # CORREÇÃO 2: Nome do serviço corrigido para 'api'
                 docker compose build --no-cache api

                 echo " PASSO 3/3: Reiniciando o serviço com a nova imagem..."
                 # CORREÇÃO 2: Nome do serviço corrigido para 'api'
                 docker compose up -d api

                 echo "✅ Deploy da API finalizado."
