name: Deploy API to VPS

on:
   # Gatilho: roda toda vez que há um push na branch 'master'
   push:
      branches:
         - master

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Deploy to VPS
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USERNAME }}
              key: ${{ secrets.VPS_SSH_KEY }}
              script: |
                 echo "🚀 Iniciando deploy da API..."
                 cd ~/meu-servidor

                 echo " PASSO 1/3: Puxando código mais recente..."
                 git -C ~/chess-analyzer pull

                 echo " PASSO 2/3: Forçando a reconstrução da imagem sem cache..."
                 docker compose build --no-cache api-backend

                 echo " PASSO 3/3: Reiniciando o serviço com a nova imagem..."
                 docker compose up -d api-backend

                 echo "✅ Deploy da API finalizado."
